services:
  backend:
    build: ./backend
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=local

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080

  db:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=task_manager
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=task_manager
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: 