spring:
  application:
    name: task-manager
  datasource:
    url: jdbc:postgresql://db:5432/task_manager
    username: task_manager
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true 